import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const dieGrotesk = localFont({
  variable: "--font-die-grotesk",
  src: [
    {
      path: "../public/assets/fonts/die-grotesk-b-bold-italic.woff2",
      weight: "700",
      style: "italic",
    },
    {
      path: "../public/assets/fonts/die-grotesk-b-bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/assets/fonts/die-grotesk-b-italic.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "../public/assets/fonts/die-grotesk-b-regular.woff2",
      weight: "400",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dieGrotesk.variable} antialiased`}>{children}</body>
    </html>
  );
}
